[project]
name = "calfem-python"
dynamic = ["version"]
description = "CALFEM for Python"
authors = [
    {name = "Jonas Lindemann", email = "jonas.lindemann@lunarc.lu.se"},
    {name = "Jonas Lindemann", email = "jonas.lindemann@gmail.com"},
]
dependencies = [
    "gmsh",
    "matplotlib",
    "numpy",
    "scipy",
    "tabulate",
]

requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}
keywords = [
    "finite element",
    "math",
    "numerics",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Education",
]

[project.urls]
Homepage = "https://github.com/CALFEM/calfem-python"
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "src/calfem/__init__.py"

[project.optional-dependencies]
visvis = [ "visvis" ]
vedo = [ "vedo" ]
pyvtk = [ "pyvtk" ]
vtk = [ "vtk" ]
qtpy = [ "qtpy" ]
pyside6 = [ "qtpy", "PySide6" ]
pyqt6 = [ "qtpy", "PyQt6" ]
io = [ "meshio" ]
plotly = [ "plotly" ]
